config/routes.rb
Rails.application.routes.draw do
  resources :sighs

  root 'sighs#new'

end

app/models/sigh.rb
class Sigh < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sighs_controller.rb
class SighsController < ApplicationController
  before_action :set_sigh, only: :destroy
  before_action :set_time_zone, only: [:new, :create]

  def new

    gon.data = Sigh.all.group_by { |t| t.created_at.strftime('%k') }.map {|k,v| [k, v.length] }.sort
    @sighs = Sigh.all.order('created_at desc').group_by { |t| t.created_at.strftime('%B %e') }
    @sigh = Sigh.new
  end

  def create
    @sigh = Sigh.new(created_at: DateTime.now.in_time_zone)

    respond_to do |format|
      if @sigh.save
        format.html { redirect_to root_path, notice: 'Sigh was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @sigh.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Sigh was successfully destroyed.' }
    end
  end

  private
    def set_sigh
      @sigh = Sigh.find(params[:id])
    end

    def sigh_params
      params.fetch(:sigh, {})
    end

    def set_time_zone
      Time.zone = 'Minsk'
    end

  def group_by_criteria

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sighs_helper.rb
module SighsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Breath</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= include_gon %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sighs/new.html.erb
<div class="page-wrapper">
    <div id="sighs-wrapper">

      <a href="#" class="button-icon toggle-history">
        <i class="fa fa-bars"></i>
      </a>

      <a href="#" class="button-icon toggle-modal">
        <i class="fa fa-line-chart"></i>
      </a>

      <%= link_to 'Breath!', sighs_path, class: 'sigh-button', method: :post %>

      <div class="sighs-stats"> </div>

    </div>

    <div id="history-wrapper">
      <% @sighs.first(14).each do |key, value| %>
          <div class="sighs-history">
              <p class="sighs-history_day"><%= key %></p>
              <div class="sighs-history_time">
                <% value.each do |sigh| %>
                    <div><%= sigh.created_at.strftime('%R') %></div>
                <% end %>
              </div>
          </div>
      <% end %>
    </div>

    <div id="chart-modal" class="modal">
      <a href="#" class="button-icon toggle-modal">
        <i class="fa fa-times"></i>
      </a>
    </div>
</div>